#! /bin/sh
sxhkd &
# cd ~/HOME/ && python3 -m http.server &
~/.config/polybar/launch.sh &
# nitrogen --restore &
compton -b &
volumeicon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
ff-theme-util &
fix_xcursor &
nm-applet &
pamac-tray &
xfce4-power-manager &
wal -i ~/Pictures/ -o wal-set &



# bspc monitor -d A S D F G H J 
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

# bspc config active_border_color \#4c566a
# bspc config normal_border_color \#4c566a
# bspc config focused_border_color \#d8dee9

bspc config top_padding 50
bspc config left_padding 12
bspc config right_padding 12
bspc config bottom_padding 12
